project_id = "wtkxyofvbillvclkcvir"

[functions.supabase-proxy]
verify_jwt = false

[functions.google-calendar]
verify_jwt = false

[functions.google-calendar-create]
verify_jwt = false

[functions.google-calendar-delete]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.subscribe-push]
verify_jwt = false

[functions.notify]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.send-wapi-reminder]
verify_jwt = false

[functions.check-client-reminders]
verify_jwt = false

[functions.schedule-reminder]
verify_jwt = false
